import type { NextPage } from 'next';
import Head from 'next/head';
import MainSection from '../components/mainSection';
import GoogleTagManager from "../components/GTM/GoogleTagManager";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Francine Nogueira Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
      <MainSection/>
      </main>
    </div>
  )
}

export default Home
